We've discussed the first three of the following, and now it's time to talk about tensors in general.

* Scalar
* Vector
* Matrix
* Tensor

A scalar can be seen as a rank zero tensor.

In [ ]:
import tensorflow as tf

x = tf.constant(4)
print(x)
print(x.ndim)

tf.Tensor(4, shape=(), dtype=int32)
0


On the other hand, a vector can be viewed as a rank one tensor, which means it has one dimension.

In [ ]:
y = tf.constant([3, 2, 7])
print(y)
print(y.ndim)

tf.Tensor([3 2 7], shape=(3,), dtype=int32)
1


A matrix is a rank two tensor. It has two dimensions. For example, a matrix A of size m by n has m rows and n columns.

In [ ]:
A = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
print(A)
print(A.ndim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
2


This concept can be extended to tensors. For instance, a tensor could have three dimensions (known as a rank three tensor), four dimensions (known as a rank four tensor), or any number of dimensions (referred to as a rank n tensor).

In [ ]:
B = tf.linspace(1, 60, 60)
tf.reshape(B, shape=(5, 2, 6))

<tf.Tensor: shape=(5, 2, 6), dtype=float64, numpy=
array([[[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]],

       [[13., 14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23., 24.]],

       [[25., 26., 27., 28., 29., 30.],
        [31., 32., 33., 34., 35., 36.]],

       [[37., 38., 39., 40., 41., 42.],
        [43., 44., 45., 46., 47., 48.]],

       [[49., 50., 51., 52., 53., 54.],
        [55., 56., 57., 58., 59., 60.]]])>

In [ ]:
C = tf.linspace(1, 60, 60)
tf.reshape(C, shape=(5, 2, 2, 3))

<tf.Tensor: shape=(5, 2, 2, 3), dtype=float64, numpy=
array([[[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]],


       [[[13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.]]],


       [[[25., 26., 27.],
         [28., 29., 30.]],

        [[31., 32., 33.],
         [34., 35., 36.]]],


       [[[37., 38., 39.],
         [40., 41., 42.]],

        [[43., 44., 45.],
         [46., 47., 48.]]],


       [[[49., 50., 51.],
         [52., 53., 54.]],

        [[55., 56., 57.],
         [58., 59., 60.]]]])>